services:
  db:
    image: postgres:16
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    image: research-repo-backend
    container_name: backend
    depends_on:
      - db
    environment:
      # Database
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}

      SPRING_SECURITY_USER_NAME: ${SPRING_SECURITY_USER_NAME}
      SPRING_SECURITY_USER_PASSWORD: ${SPRING_SECURITY_USER_PASSWORD}

      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}

      # Google OAuth
      APP_GOOGLE_CLIENT_ID: ${APP_GOOGLE_CLIENT_ID}
      APP_GOOGLE_CLIENT_SECRET: ${APP_GOOGLE_CLIENT_SECRET}
      APP_GOOGLE_REDIRECT_URI: ${APP_GOOGLE_REDIRECT_URI}

      # JWT & Auth
      APP_JWT_SECRET: ${APP_JWT_SECRET}
      APP_JWT_ACCESS_TOKEN_EXPIRY: ${APP_JWT_ACCESS_TOKEN_EXPIRY}

      APP_REFRESH_TOKEN_COOKIE_NAME: ${APP_REFRESH_TOKEN_COOKIE_NAME}
      APP_REFRESH_TOKEN_MAX_AGE: ${APP_REFRESH_TOKEN_MAX_AGE}

      # CORS
      APP_CORS_ALLOWED_ORIGINS: ${APP_CORS_ALLOWED_ORIGINS}
      APP_CORS_ALLOWED_METHODS: ${APP_CORS_ALLOWED_METHODS}
      APP_CORS_ALLOWED_HEADERS: ${APP_CORS_ALLOWED_HEADERS}
      APP_CORS_ALLOW_CREDENTIALS: ${APP_CORS_ALLOW_CREDENTIALS}

    ports:
      - "8080:8080"

    volumes:
      - ${PRIVILEGED_USERS_YAML_PATH}:/app/config/privileged-users.yaml

volumes:
  pgdata:
