# Just run it normally when in dev (auto overide prod config)
# > docker compose up -d

services:
  backend:
    command: mvn spring-boot:run
    volumes:
      - ./src:/app/src
      - ./pom.xml:/app/pom.xml
      - m2:/root/.m2

volumes:
  m2:
