spring:
  application:
    name: research-repository

  datasource:
    url: jdbc:postgresql://localhost:5432/repo_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
