spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  security:
    user:
      name: ${SPRING_SECURITY_USER_NAME}
      password: ${SPRING_SECURITY_USER_PASSWORD}

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://db:5432/research-repo-db}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

logging:
  level:
    com.acd.researchrepo: DEBUG

# Application configuration
app:
  google:
    client-id: ${APP_GOOGLE_CLIENT_ID}
    client-secret: ${APP_GOOGLE_CLIENT_SECRET}
    redirect-uri: ${APP_GOOGLE_REDIRECT_URI:postmessage}

  jwt:
    secret: ${APP_JWT_SECRET}
    access-token-expiry: ${APP_JWT_ACCESS_TOKEN_EXPIRY:3600}

  token:
    refresh-token-cookie-name: ${APP_REFRESH_TOKEN_COOKIE_NAME:refreshToken}
    refresh-token-max-age: ${APP_REFRESH_TOKEN_MAX_AGE:2592000}

  cors:
    allowed-origins: ${APP_CORS_ALLOWED_ORIGINS:http://localhost:5173}
    allowed-methods: ${APP_CORS_ALLOWED_METHODS:GET,POST,PUT,DELETE,PATCH,OPTIONS}
    allowed-headers: ${APP_CORS_ALLOWED_HEADERS:*}
    allow-credentials: ${APP_CORS_ALLOW_CREDENTIALS:true}
